/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Al-Mishkat Educational Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Subject {
  id: string;
  name: string;
  arabicName: string;
  description: string;
  icon: string;
  color: string;
  videoCount: number;
  pdfCount: number;
  imageCount: number;
  quizCount: number;
}

export type VideoItemType = (typeof VideoItemType)[keyof typeof VideoItemType];

export const VideoItemType = {
  reel: "reel",
  short: "short",
  lecture: "lecture",
} as const;

export interface VideoItem {
  id: string;
  title: string;
  description: string;
  type: VideoItemType;
  duration: string;
  thumbnailUrl: string;
  videoUrl: string;
  subjectId: string;
  uploadedAt: string;
}

export type PdfItemCategory =
  (typeof PdfItemCategory)[keyof typeof PdfItemCategory];

export const PdfItemCategory = {
  summary: "summary",
  handout: "handout",
  notes: "notes",
  reference: "reference",
} as const;

export interface PdfItem {
  id: string;
  title: string;
  description: string;
  category: PdfItemCategory;
  fileSize: string;
  pageCount: number;
  downloadUrl: string;
  subjectId: string;
  uploadedAt: string;
}

export interface ImageSnippet {
  id: string;
  title: string;
  bookTitle: string;
  author: string;
  pageRange: string;
  imageUrl: string;
  downloadUrl: string;
  subjectId: string;
}

export type QuizDifficulty =
  (typeof QuizDifficulty)[keyof typeof QuizDifficulty];

export const QuizDifficulty = {
  beginner: "beginner",
  intermediate: "intermediate",
  advanced: "advanced",
} as const;

export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface Quiz {
  id: string;
  title: string;
  description: string;
  subjectId: string;
  questionCount: number;
  passThreshold: number;
  difficulty: QuizDifficulty;
  questions: QuizQuestion[];
}

export type QuizAttemptBodyAnswersItem = {
  questionId: string;
  selectedIndex: number;
};

export interface QuizAttemptBody {
  answers: QuizAttemptBodyAnswersItem[];
}

export type QuizResultFeedbackItem = {
  questionId: string;
  correct: boolean;
  explanation: string;
};

export interface QuizResult {
  quizId: string;
  score: number;
  totalQuestions: number;
  percentage: number;
  passed: boolean;
  feedback: QuizResultFeedbackItem[];
}

export interface Pillar {
  id: string;
  name: string;
  arabicName: string;
  order: number;
  shortDescription: string;
  icon: string;
}

export type PillarDetailLinksItem = {
  title: string;
  url: string;
  description: string;
};

export interface PillarDetail {
  id: string;
  name: string;
  arabicName: string;
  order: number;
  description: string;
  arabicText: string;
  videos: VideoItem[];
  links: PillarDetailLinksItem[];
}

export interface SubmitQuestionBody {
  name: string;
  email?: string;
  question: string;
}

export interface QuestionSubmission {
  id: string;
  message: string;
  submittedAt: string;
}

export interface SearchResults {
  query: string;
  totalResults: number;
  videos: VideoItem[];
  pdfs: PdfItem[];
  images: ImageSnippet[];
  subjects: Subject[];
  pillars: Pillar[];
}

export type FeedItemType = (typeof FeedItemType)[keyof typeof FeedItemType];

export const FeedItemType = {
  video: "video",
  image: "image",
  pdf: "pdf",
} as const;

export interface FeedItem {
  id: string;
  type: FeedItemType;
  title: string;
  description: string;
  thumbnailUrl: string;
  subjectId: string;
  subjectName: string;
  createdAt: string;
}

export interface PlatformStats {
  totalVideos: number;
  totalPdfs: number;
  totalImages: number;
  totalQuizzes: number;
  totalSubjects: number;
  totalPillars: number;
}

export interface RequestUploadUrlBody {
  name: string;
  size: number;
  contentType: string;
}

export type RequestUploadUrlResponseMetadata = {
  name: string;
  size: number;
  contentType: string;
};

export interface RequestUploadUrlResponse {
  uploadURL: string;
  objectPath: string;
  metadata: RequestUploadUrlResponseMetadata;
}

export type ListSubjectVideosParams = {
  type?: ListSubjectVideosType;
};

export type ListSubjectVideosType =
  (typeof ListSubjectVideosType)[keyof typeof ListSubjectVideosType];

export const ListSubjectVideosType = {
  reel: "reel",
  short: "short",
  lecture: "lecture",
} as const;

export type SearchContentParams = {
  q: string;
  type?: SearchContentType;
};

export type SearchContentType =
  (typeof SearchContentType)[keyof typeof SearchContentType];

export const SearchContentType = {
  video: "video",
  pdf: "pdf",
  image: "image",
  quiz: "quiz",
  pillar: "pillar",
  subject: "subject",
} as const;
