/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Al-Mishkat Educational Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { ImageSnippet } from "./imageSnippet";
import type { PdfItem } from "./pdfItem";
import type { Pillar } from "./pillar";
import type { Subject } from "./subject";
import type { VideoItem } from "./videoItem";

export interface SearchResults {
  query: string;
  totalResults: number;
  videos: VideoItem[];
  pdfs: PdfItem[];
  images: ImageSnippet[];
  subjects: Subject[];
  pillars: Pillar[];
}
