/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Al-Mishkat Educational Platform API
 * OpenAPI spec version: 0.1.0
 */

export type SearchContentType =
  (typeof SearchContentType)[keyof typeof SearchContentType];

export const SearchContentType = {
  video: "video",
  pdf: "pdf",
  image: "image",
  quiz: "quiz",
  pillar: "pillar",
  subject: "subject",
} as const;
