/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Al-Mishkat Educational Platform API
 * OpenAPI spec version: 0.1.0
 */

export interface Subject {
  id: string;
  name: string;
  arabicName: string;
  description: string;
  icon: string;
  color: string;
  videoCount: number;
  pdfCount: number;
  imageCount: number;
  quizCount: number;
}
