/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Al-Mishkat Educational Platform API
 * OpenAPI spec version: 0.1.0
 */

export type VideoItemType = (typeof VideoItemType)[keyof typeof VideoItemType];

export const VideoItemType = {
  reel: "reel",
  short: "short",
  lecture: "lecture",
} as const;
